<a href="https://colab.research.google.com/github/mariacgomez-tech/Analitica-de-Negocios/blob/main/LavadoActivos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Caso De Estudio**: Detección de riesgo SARLAFT en una entidad financiera
En este documento se desarrolla y se analiza un modelo Naive Bayes para la identificación temprana de clientes con alto riesgo de incurrir en lavado de activos (SARLAFT) basandose en variables de comportamiento financiero que caracterizan a una persona activa en el sistema financiero.

De acuerdo con lo anterior, estas las variables  son:

**Edad**:  Es la edad del cliente al momento del análisis.

**Ingresos**: Ingresos recibidos por una persona como resultado de una actividad comercial.

**Egresos**: Egresos o desembolsos realizados por una persona asociados al consumo, pagos o transferencias.

**Número de tarjetas de crédito**: Número total de tarjetas de crédito activas que posee el cliente dentro del sistema financiero.

**Monto transado tarjetas**: Valor total de las transacciones realizadas por el cliente mediante tarjetas de crédito o débito.

**Porcentaje crecimiento patrimonio**: Variación porcentual del patrimonio neto de un periodo a otro.

Estas variables permiten analizar tanto la capacidad económica del cliente como la intensidad y dinámica de su comportamiento transaccional, aspectos clave en la detección de posibles señales de alerta en SARLAFT.

0. Se procede con la carga de las librerías de trabajo.

In [ ]:
import numpy as np
import pandas as pd

from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

1. Se cargan los datos de trabajo de la base de datos Lavado de Activos

In [ ]:
nxl='/content/2. LavadoActivos.xlsx'
XDB=pd.read_excel(nxl,sheet_name=0)
XDB.head(100)

XD=XDB[['edad','ingresos_usd','gastos_usd', 'num_tarjetas_credito', 'monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio']]
XD.head(10)
yd=XDB['lavado_activos']
yd.head()


,lavado_activos
0,1
1,1
2,0
3,0
4,0


2. Implementamos modelo Naive Bayes

In [ ]:
np.set_printoptions(precision=3)
mnb=GaussianNB()
mnb.fit(XD,yd)

u=mnb.theta_
sigma=mnb.var_; sigma=np.sqrt(sigma)
print("'edad','ingresos_usd','gastos_usd', 'num_tarjetas_credito', 'monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio'")
print(u)
print("Las desviaciones son:")
print(sigma)
print()
print("Los limites superiores de las variables son: ", u+sigma)
print()
print("Los limites inferiores de las variables son: ", u-sigma)

'edad','ingresos_usd','gastos_usd', 'num_tarjetas_credito', 'monto_transado_tarjetas_usd','porcentaje_crecimiento_patrimonio'
[[4.547e+01 6.691e+03 3.602e+03 1.955e+00 3.090e+03 4.469e+01]
 [4.430e+01 7.026e+04 3.871e+04 2.016e+00 3.384e+04 4.482e+01]]
Las desviaciones son:
[[1.471e+01 6.207e+03 3.219e+03 2.535e+00 2.457e+03 1.417e+01]
 [1.505e+01 1.134e+05 6.590e+04 2.557e+00 6.299e+04 1.548e+01]]

Los limites superiores de las variables son:  [[6.018e+01 1.290e+04 6.821e+03 4.490e+00 5.547e+03 5.886e+01]
 [5.935e+01 1.837e+05 1.046e+05 4.574e+00 9.683e+04 6.030e+01]]

Los limites inferiores de las variables son:  [[ 3.076e+01  4.838e+02  3.827e+02 -5.806e-01  6.336e+02  3.051e+01]
 [ 2.925e+01 -4.315e+04 -2.720e+04 -5.412e-01 -2.916e+04  2.934e+01]]


#**Análisis de Resultados**
De los resultados arrojados por el modelo, podemos observar que la categoría de clientes clasificados como alto riesgo SARLAFT presenta ingresos superiores a la categoría de clientes clasificados como bajo riesgo SARLAFT, esto sugiere que niveles elevados de ingresos pueden corresponder a flujos de dinero difíciles de justificar o inconsistentes con un posible riesgo de lavado de activos. De manera similar, los egresos también son notablemente más altos en la categoría de alto riesgo. Esto indica que estos clientes no solo reciben grandes cantidades de dinero, sino que también presentan una alta circulación dentro del sistema financiero. Este factor se vuelve aún más relevante al analizar el monto transado a través de tarjetas, el cual es muy superior en los clientes de alto riesgo en comparación con los clientes clasificados como bajo riesgo.

Las variables edad, el número de tarjetas de crédito y el porcentaje de crecimeinto del patrimonio no presentan diferencias significativas entre las categorías, lo que indica que estas características no son determinantes para la clasificación.


3. Se procede con la evaluación del modelo. Para la evaluación de este tipo de modelo se utiliza la matriz de confusión.

**Desempeño del modelo**

In [ ]:
ydp=mnb.predict(XD) #Esto es lo que el modelo aprende - ydp de pronóstico
cm=confusion_matrix(yd,ydp)
print(cm)

VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]; TDatos=len(XDB)

#1. Exactitud: Funcionamiento general del modelo (Primera métrica, como funcionó pronosticando)
Ex=(VP+VN)/(TDatos)
print("Exactitud: ",Ex)

#2. Tasa de error: % fallos del sistema
TEr=(FP+FN)/(TDatos)
print("Tasa de error: ",TEr) #Modelo que pase del 75% es muy bueno

#3. Sensibilidad: Como se  comportó con respecto a los positivos. (fila)
Se=VP/(VP+FN)
print("Sensibilidad: ",Se)

#4. Especificidad: Como se comporta pronosticando negativos
Es=VN/(VN+FP)
print("Especificidad: ",Es)

#5. Precisión: Es una versión de como se comporta el modelo frente a los positivos solamente. (columna)
Pr=VP/(VP+FP)
print("Precisión: ",Pr)

#6. Predicción Negativa: como funciona el modelo pronosticando créditos PreNegados
PrN=VN/(VN+FN)
print("Predicción Negativa: ",PrN)

[[2179   44]
 [ 145  782]]
Exactitud:  0.94
Tasa de error:  0.06
Sensibilidad:  0.8435814455231931
Especificidad:  0.9802069275753487
Precisión:  0.9467312348668281
Predicción Negativa:  0.9376075731497419


**Análisis de resultados**

De acuerdo con los resultados obtenidos, se puede observar de manera general que el modelo alcanzó una exactitud del 94%, lo que indica un muy buen desempeño en la clasificación de los clientes entre categorías de alto y bajo riesgo SARLAFT. Este resultado evidencia que el modelo logra diferenciar adecuadamente los perfiles financieros según su nivel de riesgo.

Se destaca la precisión del 94,6%, lo que indica que cuando el modelo clasifica a un cliente como de alto riesgo, en la gran mayoría de los casos  es correcto. Igualmente, se puede observar el buen comportamiento del modelo frente a la identificación de clientes de bajo riesgo, tal como lo demuestra la especificidad del 98%. Este valor indica que el modelo reconoce correctamente a casi todos los clientes que realmente no representan un riesgo significativo.

Sin embargo, la sensibilidad del 84,3% indica que algunos clientes de alto riesgo no están siendo detectados. Pero por otro lado, la predicción negativa del 93,7% confirma que la mayoría de los clientes clasificados como de bajo riesgo realmente lo son.

4. Se evalúa a un cliente

In [ ]:
XP=[58,31692,19139,2,10493,39.61]
ydc=mnb.predict([XP])
print(ydc)

if ydc==1:
  print("El ususario tiene alto riesgo de incurrir en lavado de activos")
else:
  print("El usuario no tiene riesgo de incurrir en lavado de activos")

[1]
El ususario tiene alto riesgo de incurrir en lavado de activos


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
