<a href="https://colab.research.google.com/github/mariacgomez-tech/Analitica-de-Negocios/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Caso de estudio**
En este documento se desarrolla y se analiza un modelo Naive Bayes para la PreAprobación de créditos en una entidad financiera utilizando las variaboles socioeconómicas de un solicitante de crédito.
De acuerdo con lo anterior, las variables socioeconómicas son:

**Edad**: Es la edad que posee el solicitante al momento de solicitar un crédito.

**Ingresos**: Ingresos recibidos por una persona como resultado de una actividad comercial.

**Egresos**: Son los gastos mensuales del solicitante. Gastos de personas a cargo, hijos y servicios públicos.

**Monto (EAD)**: Indica el dinero que una persona solicita a una entidad financiera como crédito.

0. Se procede con la carga d elas librerías de trabajo.

In [ ]:
import numpy as np #Librería numérica por excelencia. (pongo np para no tener que seguirla escribiendo)
import pandas as pd #Librería para la comunicación con archivos de excel

#Librerías específicas
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

1. Se cargan los datos de trabajo de la base de datos a la BaseAAA

In [ ]:
nxl='/content/1. SolicitantesCrédito(USD) (1).xlsx' #Las hojas de excel se empiezan a contar desde 0
XDB=pd.read_excel(nxl,sheet_name=1)
#XDB.head(100) #Es para mostrar la base de datos cargada (el numero que esta entre parentesis es el número de filas que muestra)

#Seleccionamos variables de trabajo
XD=XDB[['Edad', 'Ingresos', 'Egresos', 'Monto (EAD)']] #Variables de trabajo
XD.head(10)
yd=XDB[['PreApr']] #Variable de decisión
yd.head()

,PreApr
0,1
1,1
2,0
3,1
4,1


2. Implementamos modelo Naive Bayes

In [ ]:
mnb=GaussianNB()
mnb.fit(XD,yd) #Ajustar variables Entrada - Salida

#Mostramos las medias de las variables
u=mnb.theta_
sigma=mnb.var_; sigma=np.sqrt(sigma) #Varianza es sigma al cuadrado. La desviación es la raiz cuadrada de sigma
print("'Edad', 'Ingresos', 'Egresos', 'Monto (EAD)'")
print(u)
print("Las desviaciones son:")
print(sigma)


'Edad', 'Ingresos', 'Egresos', 'Monto (EAD)'
[[  40.98411626  431.42680644  401.54995644  289.41445941]
 [  41.10752688 1029.98947251  900.19312144  781.2021157 ]]
Las desviaciones son:
[[ 12.21303268 325.79791497 342.77286087 235.95783541]
 [ 12.25106493 472.43342807 525.43337837 469.90038088]]


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


**Análisis de resultados**

De los resultados arrojados por el modelo, podemos observar que la categoría de PreAprobados posee ingresos superiores a las categorías de PreNegados, esto indica claramente la predominancia de la variable para aprobar créditos. Es importante mencianar que la edad es mayor para los PreAprobados que para los Prenegados, lo que indica que el banco busca personas con mayor experiencia crediticia. Podemos decir igualmente, que los PreAprobados tienen ingresos superiores a los de la categoría PreNegados, sin embargo, los PreAprobados están solicitando montos superiores a los de la categoría PreNegados, esto es un indicador de la capacidad de este grupo para hacer frente a un crédito.

3. Se procede con la evaluación del modelo. Para la evaluación de este tipo de modelo se utiliza la matriz de confusión.

**Desempeño del modelo**

In [ ]:
ydp=mnb.predict(XD) #Esto es lo que el modelo aprende - ydp de pronóstico
cm=confusion_matrix(yd,ydp)
print(cm)
#Revisar diagonal principal. La suma de las filas es el total de datos (1 son preAprobados, 0 PreNegados)
#En la tabla: Los verdaderos negativos el modelo fue capaz de pegarle a los datos (0-0), Los falsos positivos (el modelo falla 0-1)
#Verdaderos positivos : el modelo se encuentra un 1 en loa base de datos y es capaz de pronosticarlo. Falsos Negativos: el modelo falla  1-0

#Se determinan las métricas de la matriz de confusión
VN=cm[0,0]; FP=cm[0,1]; FN=cm[1,0]; VP=cm[1,1]; TDatos=len(XDB)

#1. Exactitud: Funcionamiento general del modelo (Primera métrica, como funcionó pronosticando)
Ex=(VP+VN)/(TDatos)
print("Exactitud: ",Ex)

#2. Tasa de error: % fallos del sistema
TEr=(FP+FN)/(TDatos)
print("Tasa de error: ",TEr) #Modelo que pase del 75% es muy bueno

#3. Sensibilidad: Como se  comportó con respecto a los positivos. (fila)
Se=VP/(VP+FN)
print("Sensibilidad: ",Se)

#4. Especificidad: Como se comporta pronosticando negativos
Es=VN/(VN+FP)
print("Especificidad: ",Es)

#5. Precisión: Es una versión de como se comporta el modelo frente a los positivos solamente. (columna)
Pr=VP/(VP+FP)
print("Precisión: ",Pr)

#6. Predicción Negativa: como funciona el modelo pronosticando créditos PreNegados
PrN=VN/(VN+FN)
print("Predicción Negativa: ",PrN)


[[2502  457]
 [ 937 1946]]
Exactitud:  0.7613830879835672
Tasa de error:  0.23861691201643273
Sensibilidad:  0.6749913284772806
Especificidad:  0.8455559310577898
Precisión:  0.8098210570120683
Predicción Negativa:  0.7275370747310265


**Análisis de resultados**

De acuerdo con los resultados, podemos observar de manera general que el modelo alcanzó una exactitud por encima del 75% en proomedio, lo que indica el buen comportamiento del modelo frente a la clasificación de los solicitantes de crédito frente a PreApr y la PreNeg.

Se destaca la precisión con un 80,9%, lo que indica el buen funcionamiento del modelo frente a la preApr de créditos. Igualmente, se puede observar el buen comportamiento del modelo frente a la preNegación de créditoss, tal y como lo demuestra el indice de especifidad del modelo, el cual estuvo por encima del 84% en promedio. Es importante mencionar que la exactitud queda por debajo del 80%, ya que esta métrica se ve afectada por los errores en la clasificación de solicitantes de crédito, lo que se evidencia a través de la sensibilidad y la predicción Negativa.

4. Evaluamos un solicitante

In [ ]:
XP=[34,1500,800,1000]
ydc=mnb.predict([XP])
print(ydc)

if ydc==1:
  print("El solicitante es PreAprobado")
else:
  print("El solicitante es PreNegado")

[1]
El solicitante es PreAprobado


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
